### ISSUE TITLE
Local directory is not mounting! How will I access local images in application

### ISSUE THREAD

**Issue by Utsaww** [maxnth/LAREX_Docker#3]
I am using the docker image on the window, I have images in the folder name news whose location is this -`/Users/upadh/OneDrive/Desktop/news` now I tried to mount this but not working only showing a default single image in the application.

**Image for more info** How Will I access the images of the system in application?

![image](https://user-images.githubusercontent.com/81962784/222966451-beeabb38-cd33-4a32-8084-ac284774774e.png)

**Comment by maxnth** [comment]
Hi, I just updated the repository and Docker image on Docker Hub so that both use the latest stable release of LAREX as well as the updated config file format, so please pull the image to use the latest image.

If you want to access the projects under `/Users/upadh/OneDrive/Desktop/news` you just have to set the `Host path` to `/Users/upadh/OneDrive/Desktop/news` and the `Container path` to `/home/books` in the Docker Desktop UI (or `-v /Users/upadh/OneDrive/Desktop/news:/home/books/` when using the CLI). 
Make sure that there aren't any permissions set for the mounted volume that might prohibit Docker from accessing the subdirectories / files.

**Comment by Utsaww** [comment]
Thank you so much for the quick reply! I did exactly the same and got this error you can see in the image attached, I am using windows 11

![image](https://user-images.githubusercontent.com/81962784/223167833-ecef6442-ec47-4933-8549-d2c330947892.png)

**Comment by maxnth** [comment]
I don't use Windows and / or the Docker Desktop UI so I can't reproduce this but judging from the error message this should be related to the issue described [here](https://github.com/docker/for-win/issues/1560).

If possible I would advise to just use the Powershell (or even WSL2) for creating / running the container, we have various Windows users doing this for OCR4all and it seems to work well enough. 

You might also have to add the drive prefix (e. g. `C:\`) to your path (but as I'm not a Windows user I'm not too sure whether that's necessary or not...).
